import { library } from '@fortawesome/fontawesome-svg-core';
import {
  fas,
  faHome,
  faLightbulb,
  faInfoCircle,
  faEnvelope,
  faAngleDoubleRight,
  faPlus,
  faPhoneSquareAlt,
  faPalette,
  faDice,
  faDragon,
  faGlobeEurope,
  faDumbbell,
  faBook,
  faVideo,
  faChess,
  faCookie,
  faPaintBrush,
  faChevronRight,
  faChevronLeft,
  faEllipsisH,
  faCode,
} from '@fortawesome/free-solid-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';

import {
  fab,
  faLinkedin,
  faGithub,
  faArtstation,
  faInstagram,
  faDev,
  faHtml5,
  faCss3Alt,
  faJsSquare,
  faNode,
  faReact,
  faBootstrap,
  faSass,
  faGit,
  faSlack,
  faDiscord,
  faTrello,
  faYarn,
  faNpm,
  faLinux,
  faFontAwesomeFlag,
} from '@fortawesome/free-brands-svg-icons';

library.add(fas, far, fab);

library.add(
  faHome,
  faLightbulb,
  faInfoCircle,
  faEnvelope,
  faAngleDoubleRight,
  faPlus,
  faPhoneSquareAlt,
  faLinkedin,
  faGithub,
  faArtstation,
  faInstagram,
  faDev,
  faPalette,
  faDice,
  faDragon,
  faGlobeEurope,
  faDumbbell,
  faBook,
  faVideo,
  faChess,
  faCookie,
  faPaintBrush,
  faChevronRight,
  faHtml5,
  faChevronLeft,
  faCss3Alt,
  faJsSquare,
  faNode,
  faReact,
  faBootstrap,
  faEllipsisH,
  faSass,
  faGit,
  faSlack,
  faDiscord,
  faTrello,
  faYarn,
  faNpm,
  faLinux,
  faCode,
  faFontAwesomeFlag,
);
